# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_final',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 20, 8, 27, 759838), null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 20, 8, 27, 759808), null=True),
        ),
    ]
