# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 00:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20180813_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_final',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 19, 28, 36, 762014), null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 19, 28, 36, 762014), null=True),
        ),
    ]
