# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_auto_20180815_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_final',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 1, 4, 1, 660470), null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 1, 4, 1, 660470), null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.Usuario'),
        ),
    ]
