# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_auto_20180816_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 1, 24, 42, 98021), null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_final',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 1, 24, 42, 98021), null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 1, 24, 42, 98021), null=True),
        ),
    ]
