# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_auto_20180816_0124'),
        ('evento', '0002_auto_20180813_2028'),
    ]

    operations = [
    ]
