# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0009_auto_20180816_1608'),
        ('evento', '0002_auto_20180813_2008'),
    ]

    operations = [
    ]
