# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0010_merge_20180816_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_final',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 16, 11, 15, 100521), null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 16, 11, 15, 100490), null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 16, 11, 15, 100590), null=True),
        ),
    ]
